basic.showIcon(IconNames.Heart)

input.onButtonPressed(Button.A, function() {
    drone.takeOffAction()
    basic.pause(1000)
    drone.setDroneHeight(80)
    basic.pause(1000)
    drone.moveAction(drone.DirectionOptions.Forward, 150)
    basic.pause(1000)
    drone.rotationAction(drone.AngleOptions.Left, 90)
    basic.pause(1000)
    drone.moveAction(drone.DirectionOptions.Left, 150)
    basic.pause(1000)
    drone.landingAction()
    let vtg = drone.droneVoltage()
    basic.showNumber(vtg)
})