basic.showIcon(IconNames.Heart)
//Drones.initModule()

input.onButtonPressed(Button.A, function() {
    //Drones.Basic_action(Drones.Basicoptions.Takeoff)
    //basic.pause(1000)
    //Drones.UAV_altitude(80)
    //basic.pause(1000)
    //Drones.Move_action(Drones.Directionoptions.Forward, 150)
    //basic.pause(1000)
    //Drones.Rotation_action(Drones.Angleoptions.Left, 90)
    //basic.pause(1000)
    //Drones.Move_action(Drones.Directionoptions.Left, 150)
    //basic.pause(1000)
    //Drones.Basic_action(Drones.Basicoptions.Landing)
    //let vtg = Drones.Get_Sensor(Drones.Sensoroptions.Voltage)
    //basic.showNumber(vtg)
    Drones.Move_actionTime(Drones.Directionoptions.Forward, 3)
})